project_name: uif_service
builds:
  - id: uif1
    main: ./
    targets:
      - darwin_amd64_v1
      - darwin_arm64
      - linux_amd64_v1
      - linux_arm64
  - id: uif2
    main: ./
    ldflags:
      - -H=windowsgui
    targets:
      - windows_amd64_v1
      - windows_arm64
